#!/bin/bash
# Bundle the project into a clean zip that can be executed and published.
# Excludes build artifacts, virtual environments, and runtime data.

set -e

DEST="/home/z/my-project/download/real-estate-voice-agent.zip"
ROOT="/home/z/my-project"

# Remove any previous bundle
rm -f "$DEST"

# Create a staging directory with just the files we want
STAGE="/tmp/rea-stage"
rm -rf "$STAGE"
mkdir -p "$STAGE/real-estate-voice-agent"

cd "$ROOT"

# Copy top-level project files (frontend + scripts + docs)
cp README.md "$STAGE/real-estate-voice-agent/"
cp package.json "$STAGE/real-estate-voice-agent/"
cp bun.lock "$STAGE/real-estate-voice-agent/" 2>/dev/null || true
cp next.config.ts "$STAGE/real-estate-voice-agent/"
cp tsconfig.json "$STAGE/real-estate-voice-agent/"
cp tailwind.config.ts "$STAGE/real-estate-voice-agent/"
cp postcss.config.mjs "$STAGE/real-estate-voice-agent/"
cp components.json "$STAGE/real-estate-voice-agent/"
cp eslint.config.mjs "$STAGE/real-estate-voice-agent/"
cp next-env.d.ts "$STAGE/real-estate-voice-agent/"
cp .env.example "$STAGE/real-estate-voice-agent/"

# Copy src/ (frontend code)
cp -r src "$STAGE/real-estate-voice-agent/"

# Copy public/ (static assets)
cp -r public "$STAGE/real-estate-voice-agent/" 2>/dev/null || true

# Copy prisma/ (database schema)
cp -r prisma "$STAGE/real-estate-voice-agent/" 2>/dev/null || true

# Copy scripts/
cp -r scripts "$STAGE/real-estate-voice-agent/"

# Copy backend/ (excluding venv, __pycache__, runtime data)
mkdir -p "$STAGE/real-estate-voice-agent/backend"
cp -r backend/app "$STAGE/real-estate-voice-agent/backend/"
cp -r backend/data "$STAGE/real-estate-voice-agent/backend/"
cp -r backend/documents "$STAGE/real-estate-voice-agent/backend/"
cp -r backend/docs "$STAGE/real-estate-voice-agent/backend/"
cp backend/README.md "$STAGE/real-estate-voice-agent/backend/"
cp backend/SETUP.md "$STAGE/real-estate-voice-agent/backend/"
cp backend/CHANGES_SUMMARY.md "$STAGE/real-estate-voice-agent/backend/"
cp backend/DEPLOYMENT_GUIDE.md "$STAGE/real-estate-voice-agent/backend/"
cp backend/.env.example "$STAGE/real-estate-voice-agent/backend/"
cp backend/.gitignore "$STAGE/real-estate-voice-agent/backend/"
cp backend/requirements.txt "$STAGE/real-estate-voice-agent/backend/"
cp backend/database_schema.sql "$STAGE/real-estate-voice-agent/backend/"
cp backend/dashboard.html "$STAGE/real-estate-voice-agent/backend/"
cp backend/apply_schema.py "$STAGE/real-estate-voice-agent/backend/"
cp backend/demo_script.py "$STAGE/real-estate-voice-agent/backend/" 2>/dev/null || true

# Clean up any __pycache__ and .pyc that snuck in
find "$STAGE" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" -name "*.pyc" -delete 2>/dev/null || true

# Remove the seed run-time files (they get regenerated by the seed script)
# Keep the seeded conversation_memory.json so the agent has memory out of the box
# but remove the model pickle (gets regenerated on first run)
rm -f "$STAGE/real-estate-voice-agent/backend/app/data/conversation_model.pkl"

# Add a top-level .gitignore
cat > "$STAGE/real-estate-voice-agent/.gitignore" <<'EOF'
# Python
__pycache__/
*.py[cod]
*.so
.Python
venv/
env/
ENV/
.pytest_cache/
*.egg-info/

# Node
node_modules/
.next/
out/
build/

# Environment
.env
.env.local
.env.*.local

# Database
*.db
*.sqlite3

# Runtime data
backend/app/data/conversation_memory.json
backend/app/data/conversation_model.pkl
backend/app/data/call_history.json
backend/app/data/lead_memory.json

# Logs
*.log
logs/

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo
EOF

# Create the zip
cd "$STAGE"
zip -qr "$DEST" real-estate-voice-agent/

# Cleanup
rm -rf "$STAGE"

# Report
echo "Created: $DEST"
ls -la "$DEST"
echo ""
echo "Contents:"
unzip -l "$DEST" | tail -25
echo ""
echo "Total file count:"
unzip -l "$DEST" | tail -1
